'use strict';

const STORAGE_KEY = 'miUniversidadV2';
const DAYS = ['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
const NAV = [
  ['dashboard','Inicio','house'],['subjects','Materias','book'],['tasks','Tareas','check2-square'],['schedule','Horario','calendar3'],
  ['calendar','Calendario','calendar-event'],['teachers','Profesores','person-badge'],['classmates','Compañeros','people'],['attendance','Asistencia','clipboard-check'],
  ['exams','Exámenes','journal-check'],['stats','Estadísticas','bar-chart'],['goals','Objetivos','bullseye'],['notes','Notas','journal-text'],['settings','Configuración','gear']
];

const RAW_SCHEDULE = [
 ['07:00','07:45','CYT (Herrera)','CYT (Herrera)','CYT (Herrera)','CYT (Herrera)','M2.3 (Luis)'],
 ['07:45','08:30','M2.6 (Montaño)','ING (Glenda)','LENG (Sandra)','CYV (Paz)','M2.6 (Montaño)'],
 ['08:30','09:15','M2.7 (AL)','M2.2 (Luis)','M2.1 (Luis)','OPV (Rene)','CYV (Paz)'],
 ['09:15','09:45','RECESO 1','RECESO 1','RECESO 1','RECESO 1','RECESO 1'],
 ['09:45','10:30','LENG (Sandra)','M2.1 (Luis)','M2.7 (Rene)','INGTE (Glenda)','M2.1 (Luis)'],
 ['10:30','11:15','CYV (Paz)','CYV (Paz)','CYV (Paz)','MATE (Ricardo)','MATE (Ricardo)'],
 ['11:15','12:00','ING (Glenda)','OPV (Rene)','ING (Glenda)','MATE (Ricardo)','CYT (Delmy)'],
 ['12:00','12:40','RECESO 2','RECESO 2','RECESO 2','RECESO 2','RECESO 2'],
 ['12:40','13:25','M2.8 (Luis)','M2.4 (Luis)','CYT (Delmy)','M2.2 (Luis)','LENG (Sandra)'],
 ['13:25','14:10','M2.1 (Luis)','MATE (Ricardo)','M2.4 (Luis)','LENG (Sandra)','M2.8 (Luis)'],
 ['14:10','14:20','RECESO 3','RECESO 3','RECESO 3','RECESO 3','RECESO 3'],
 ['14:20','15:05','MATE (Ricardo)','LENG (Sandra)','MATE (Ricardo)','M2.3 (Luis)','M2.5 (Luis)'],
 ['15:05','15:50','M2.5 (Luis)','—','—','—','—']
];

function uid(){return (crypto && crypto.randomUUID) ? crypto.randomUUID() : 'id-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function parseClock(t){const [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m}
function formatDate(value){if(!value)return '';const d=new Date(value+'T00:00:00');return d.toLocaleDateString('es-SV',{day:'2-digit',month:'2-digit',year:'numeric'})}
function todayIndex(){const d=new Date().getDay();return d===0?6:d-1}
function nowMinutes(){const d=new Date();return d.getHours()*60+d.getMinutes()}
function parseScheduleCell(text){
  if(!text || text==='—') return null;
  if(text.startsWith('RECESO')) return {break:true,name:text,teacher:''};
  const m=text.match(/^(.+?)\s*\((.+)\)$/);
  return {break:false,name:m?m[1].trim():text.trim(),teacher:m?m[2].trim():''};
}
function originalSchedule(){
  return RAW_SCHEDULE.flatMap(row=>row.slice(2).map((cell,day)=>{
    const p=parseScheduleCell(cell); if(!p)return null;
    return {id:uid(),day,start:row[0],end:row[1],name:p.name,teacher:p.teacher,break:p.break,room:''};
  }).filter(Boolean));
}
function emptyState(){return {schedule:originalSchedule(),subjects:[],tasks:[],teachers:[],classmates:[],attendance:[],events:[],exams:[],notes:[],goals:[],theme:'light',notifications:true}}
function seedFromSchedule(state){
  const subjects=new Map(), teachers=new Map();
  state.schedule.filter(x=>!x.break).forEach(x=>{
    if(!subjects.has(x.name)) subjects.set(x.name,{id:uid(),name:x.name,code:x.name,teacher:x.teacher,room:x.room||'',schedule:'',color:'#6366f1',description:'',active:true});
    if(x.teacher && !teachers.has(x.teacher)) teachers.set(x.teacher,{id:uid(),name:x.teacher,subject:x.name,email:'',description:'',notes:'',favorite:false,rating:0});
  });
  state.subjects=[...subjects.values()]; state.teachers=[...teachers.values()]; return state;
}
function validState(x){return x && Array.isArray(x.schedule) && Array.isArray(x.subjects) && Array.isArray(x.tasks) && Array.isArray(x.teachers) && Array.isArray(x.classmates) && Array.isArray(x.attendance) && Array.isArray(x.events) && Array.isArray(x.exams) && Array.isArray(x.notes) && Array.isArray(x.goals)}
function loadState(){
  try{
    const raw=localStorage.getItem(STORAGE_KEY);
    if(raw){const x=JSON.parse(raw); if(validState(x)){return x}}
  }catch(e){console.warn('Se ignoraron datos locales dañados.',e)}
  const state=seedFromSchedule(emptyState()); saveState(state); return state;
}
let state=loadState();
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){console.error('No se pudo guardar en localStorage',e)}}

function currentClass(){const d=todayIndex(),n=nowMinutes();return state.schedule.find(x=>x.day===d && parseClock(x.start)<=n && n<parseClock(x.end))||null}
function nextClass(){const d=todayIndex(),n=nowMinutes();return state.schedule.filter(x=>!x.break&&x.day===d&&parseClock(x.start)>n).sort((a,b)=>parseClock(a.start)-parseClock(b.start))[0]||null}
function classesToday(day=todayIndex()){return state.schedule.filter(x=>x.day===day).sort((a,b)=>parseClock(a.start)-parseClock(b.start))}
function activeNav(key){return NAV.map(([id,label,icon])=>`<a class="nav-link ${id===key?'active':''}" href="#${id}"><i class="bi bi-${icon}"></i><span>${label}</span></a>`).join('')}
function renderShell(key,content){
  const label=(NAV.find(x=>x[0]===key)||['','',''])[1];
  document.getElementById('app').innerHTML=`
  <aside class="sidebar" id="sidebar">
    <div class="brand"><i class="bi bi-mortarboard-fill"></i><div class="brand-text">Mi Asistente<small>Asistente académico personal</small></div></div>
    <div class="nav-title">Mi espacio</div>${activeNav(key)}
  </aside>
  <main class="main">
    <div class="mobilebar"><button class="btn btn-soft" onclick="toggleMenu()"><i class="bi bi-list"></i></button><strong>Mi Asistente</strong><button class="btn btn-soft" onclick="toggleTheme()"><i class="bi bi-moon-stars"></i></button></div>
    <header class="topbar">
      <div><h1 class="page-title">${key==='dashboard'?'¡Hola! 👋':'Mi '+esc(label.toLowerCase())}</h1><div class="muted">${new Date().toLocaleDateString('es-SV',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div></div>
      <div class="top-actions"><div class="search-wrap"><input id="globalSearch" class="form-control desktop-search" placeholder="Buscar en tu asistente..." autocomplete="off" oninput="globalSearch(this.value)"><div id="searchResults"></div></div><button class="btn btn-soft" onclick="toggleTheme()"><i class="bi bi-moon-stars"></i></button></div>
    </header>
    <section class="fade-in">${content}</section>
  </main>`;
  document.querySelectorAll('.nav-link').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=900)toggleMenu()}));
  applyTheme();
}
function statCard(icon,value,label){return `<div class="col-6 col-xl-2"><div class="cardx stat-card"><div class="iconbox"><i class="bi bi-${icon}"></i></div><div><div class="stat-value">${value}</div><small class="muted">${label}</small></div></div></div>`}
function dashboard(){
  const pending=state.tasks.filter(x=>x.status!=='Completada').length, done=state.tasks.filter(x=>x.status==='Completada').length;
  const today=classesToday().filter(x=>!x.break), current=currentClass(), next=nextClass();
  const att=state.attendance.flatMap(x=>x.records||[]); const present=att.filter(x=>x.status==='Presente').length; const attPct=att.length?Math.round(present/att.length*100):0;
  const activity=current ? (current.break?`<div class="breakbox">☕ <strong>RECESO ACTUAL</strong><br>${current.start} - ${current.end}</div>`:`<div class="classbox current"><strong>🔵 CLASE ACTUAL</strong><div class="fs-4 fw-bold mt-1">${esc(current.name)}</div><div>👨‍🏫 ${esc(current.teacher)}</div><div>🕐 ${current.start} - ${current.end}</div></div>`) : next ? `<div class="classbox"><strong>⏭️ TU PRÓXIMA CLASE</strong><div class="fs-4 fw-bold mt-1">${esc(next.name)}</div><div>👨‍🏫 ${esc(next.teacher)}</div><div>🕐 ${next.start} - ${next.end}</div></div>` : `<div class="empty">🎉 Ya terminaste tus clases por hoy.</div>`;
  renderShell('dashboard',`
    <div class="cardx hero mb-3"><div class="row align-items-center g-3"><div class="col-lg-8"><div class="muted mb-2">Tu espacio universitario</div><div class="display">Organiza tus clases, tareas y progreso desde un solo lugar.</div><p class="muted mt-2 mb-0">Todo se guarda localmente en este navegador.</p></div><div class="col-lg-4"><div class="cardx compact"><div class="muted">Hoy</div><div class="fs-3 fw-bold">${today.length} clases</div><div class="muted">Asistencia acumulada: ${attPct}%</div></div></div></div></div>
    <div class="row g-3">${statCard('book',state.subjects.length,'Materias')}${statCard('check2-square',pending,'Tareas pendientes')}${statCard('check-circle',done,'Completadas')}${statCard('calendar3',today.length,'Clases de hoy')}${statCard('people',state.classmates.length,'Compañeros')}${statCard('person-badge',state.teachers.length,'Profesores')}</div>
    <div class="row g-3 mt-1"><div class="col-lg-7"><div class="cardx"><div class="section-heading"><h3>📚 Estado de hoy</h3><span class="pill pill-progress">${DAYS[todayIndex()]}</span></div>${activity}<div class="quick-grid mt-3"><a class="quick" href="#tasks">📝<br><strong>Tareas</strong><br><small class="muted">${pending} pendientes</small></a><a class="quick" href="#schedule">📅<br><strong>Horario</strong><br><small class="muted">Ver semana</small></a><a class="quick" href="#attendance">✅<br><strong>Asistencia</strong><br><small class="muted">${attPct}% registrada</small></a><a class="quick" href="#stats">📊<br><strong>Estadísticas</strong><br><small class="muted">Ver progreso</small></a></div></div></div><div class="col-lg-5"><div class="cardx"><div class="section-heading"><h3>⏰ Próximas entregas</h3></div>${upcomingTasks()}</div></div></div>
    <div class="cardx mt-3"><div class="section-heading"><h3>📅 Horario de hoy</h3><a class="btn btn-sm btn-soft" href="#schedule">Ver horario completo</a></div>${renderDayMobile(todayIndex())}</div>`);
}
function upcomingTasks(){const a=state.tasks.filter(x=>x.status!=='Completada').slice().sort((a,b)=>(a.date||'9999') .localeCompare(b.date||'9999')).slice(0,5);if(!a.length)return '<div class="empty">No tienes tareas pendientes 🎉</div>';return a.map(x=>`<div class="border-bottom py-2"><strong>${esc(x.name)}</strong><br><small class="muted">${esc(x.subject||'Sin materia')} · ${formatDate(x.date)} ${esc(x.time||'')}</small></div>`).join('')}
function renderDayMobile(day){const arr=classesToday(day);if(!arr.length)return '<div class="empty">No hay clases.</div>';return `<div class="mobile-day">${arr.map(x=>x.break?`<div class="breakbox">☕ <strong>${x.start} - ${x.end}</strong><br>${esc(x.name)}</div>`:`<div class="cardx compact mb-2"><strong>${x.start} - ${x.end}</strong><div class="classbox mt-2">📚 ${esc(x.name)}<br>👨‍🏫 ${esc(x.teacher)}${x.room?`<br>📍 ${esc(x.room)}`:''}</div></div>`).join('')}</div>`}
function renderWeekTable(){return `<div class="schedule-wrap schedule-desktop"><table class="schedule-table"><thead><tr><th>Hora</th>${DAYS.slice(0,5).map(d=>`<th>${d}</th>`).join('')}</tr></thead><tbody>${RAW_SCHEDULE.map(row=>`<tr><td class="time-cell">${row[0]}<br>${row[1]}</td>${row.slice(2).map(cell=>{const p=parseScheduleCell(cell);return `<td>${!p?'':p.break?`<div class="breakbox">☕ ${esc(cell)}</div>`:`<div class="classbox">📚 <strong>${esc(p.name)}</strong><br>👨‍🏫 ${esc(p.teacher)}</div>`}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
function schedule(){renderShell('schedule',`<div class="action-row mb-3"><button class="btn btn-primary" onclick="scheduleForm()">➕ Agregar clase</button><button class="btn btn-soft" onclick="restoreSchedule()">🔄 Restaurar horario original</button></div><div class="cardx"><div class="section-heading"><h3>Horario semanal</h3><span class="muted">Las horas originales se mantienen aquí como referencia.</span></div>${renderWeekTable()}<div class="mobile-day">${DAYS.slice(0,5).map((d,i)=>`<div class="cardx compact mb-3"><h4 class="fw-bold">📅 ${d}</h4>${renderDayMobile(i)}</div>`).join('')}</div></div><div class="cardx mt-3"><div class="section-heading"><h3>Mis clases editables</h3><span class="muted">Puedes editar o eliminar las clases agregadas.</span></div>${state.schedule.filter(x=>!x.break).map(x=>`<div class="d-flex justify-content-between align-items-center border-bottom py-2 gap-2"><div><strong>${DAYS[x.day]} · ${x.start}-${x.end}</strong><br><span class="muted">${esc(x.name)} · ${esc(x.teacher)}${x.room?' · '+esc(x.room):''}</span></div><div class="action-row"><button class="btn btn-sm btn-soft" onclick="scheduleForm('${x.id}')">Editar</button><button class="btn btn-sm btn-outline-danger" onclick="removeSchedule('${x.id}')">Eliminar</button></div></div>`).join('')}</div>`)}

function pageHeader(title,button){return `<div class="section-heading"><h2>${title}</h2>${button||''}</div>`}
function subjects(){renderShell('subjects',`${pageHeader('📚 Mis materias','<button class="btn btn-primary" onclick="subjectForm()">➕ Agregar materia</button>')}<div class="row g-3">${state.subjects.length?state.subjects.map(x=>`<div class="col-md-6 col-xl-4"><div class="cardx"><div class="d-flex justify-content-between gap-2"><h4 class="fw-bold mb-1">${esc(x.name)}</h4><span class="pill" style="background:${esc(x.color||'#6366f1')};color:#fff">${esc(x.code||x.name)}</span></div><div class="muted">👨‍🏫 ${esc(x.teacher||'Sin docente')}</div><div class="muted">📍 ${esc(x.room||'Aula no registrada')}</div><p class="mt-3 mb-3">${esc(x.description||'Sin descripción.')}</p><div class="action-row"><button class="btn btn-sm btn-soft" onclick="subjectForm('${x.id}')">Editar</button><button class="btn btn-sm btn-outline-danger" onclick="removeItem('subjects','${x.id}')">Eliminar</button></div></div></div>`).join(''):'<div class="col-12"><div class="empty">No hay materias adicionales. Las materias del horario ya están cargadas automáticamente.</div></div>'}</div>`)}
function subjectForm(id){const x=state.subjects.find(a=>a.id===id)||{};openModal(id?'Editar materia':'Nueva materia',`<div class="row g-3"><div class="col-md-8"><label class="form-label">Nombre</label><input id="m_name" class="form-control" value="${esc(x.name||'')}"></div><div class="col-md-4"><label class="form-label">Código</label><input id="m_code" class="form-control" value="${esc(x.code||'')}"></div><div class="col-md-6"><label class="form-label">Docente</label><input id="m_teacher" class="form-control" value="${esc(x.teacher||'')}"></div><div class="col-md-6"><label class="form-label">Aula</label><input id="m_room" class="form-control" value="${esc(x.room||'')}"></div><div class="col-md-3"><label class="form-label">Color</label><input id="m_color" type="color" class="form-control form-control-color" value="${x.color||'#6366f1'}"></div><div class="col-12"><label class="form-label">Descripción</label><textarea id="m_desc" class="form-control" rows="3">${esc(x.description||'')}</textarea></div></div>`,()=>{const n={id:id||uid(),name:m('m_name').value.trim(),code:m('m_code').value.trim(),teacher:m('m_teacher').value.trim(),room:m('m_room').value.trim(),color:m('m_color').value,description:m('m_desc').value.trim(),active:true};if(!n.name)return alert('Escribe el nombre de la materia.');if(id)Object.assign(x,n);else state.subjects.push(n);saveState();closeModal();subjects();toast('Materia guardada')})}

function taskFilters(){return `<div class="filter-row"><input id="taskSearch" class="form-control" placeholder="Buscar tarea..." oninput="renderTaskList()"><select id="taskStatus" class="form-select" style="max-width:190px" onchange="renderTaskList()"><option value="">Todos los estados</option><option>Pendiente</option><option>En progreso</option><option>Completada</option></select><select id="taskPriority" class="form-select" style="max-width:170px" onchange="renderTaskList()"><option value="">Todas las prioridades</option><option>Alta</option><option>Media</option><option>Baja</option></select></div><div id="taskList"></div>`}
function tasks(){renderShell('tasks',`${pageHeader('📝 Mis tareas','<button class="btn btn-primary" onclick="taskForm()">➕ Agregar tarea</button>')}${taskFilters()}`);renderTaskList()}
function renderTaskList(){const box=document.getElementById('taskList');if(!box)return;const q=(document.getElementById('taskSearch')?.value||'').toLowerCase(),st=document.getElementById('taskStatus')?.value||'',pr=document.getElementById('taskPriority')?.value||'';let arr=state.tasks.filter(x=>(!q||`${x.name} ${x.subject} ${x.description}`.toLowerCase().includes(q))&&(!st||x.status===st)&&(!pr||x.priority===pr)).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));box.innerHTML=arr.length?`<div class="row g-3">${arr.map(x=>`<div class="col-md-6 col-xl-4"><div class="cardx"><div class="d-flex justify-content-between gap-2"><h4 class="fw-bold">${esc(x.name)}</h4><span class="pill ${x.priority==='Alta'?'pill-high':x.priority==='Media'?'pill-mid':'pill-low'}">${esc(x.priority)}</span></div><div class="muted">📚 ${esc(x.subject||'Sin materia')}</div><div class="mt-2">📅 ${formatDate(x.date)} ${esc(x.time||'')}</div><p class="muted mt-2">${esc(x.description||'')}</p><span class="pill ${x.status==='Completada'?'pill-done':x.status==='En progreso'?'pill-progress':'pill-pending'}">${esc(x.status)}</span><div class="action-row mt-3">${x.status!=='Completada'?`<button class="btn btn-sm btn-success" onclick="completeTask('${x.id}')">✓ Completar</button>`:''}<button class="btn btn-sm btn-soft" onclick="taskForm('${x.id}')">Editar</button><button class="btn btn-sm btn-outline-danger" onclick="removeItem('tasks','${x.id}')">Eliminar</button></div></div></div>`).join('')}</div>`:'<div class="empty">No se encontraron tareas.</div>'}
function taskForm(id){const x=state.tasks.find(a=>a.id===id)||{};const subjectOptions=state.subjects.map(s=>`<option ${s.name===x.subject?'selected':''}>${esc(s.name)}</option>`).join('');openModal(id?'Editar tarea':'Nueva tarea',`<div class="row g-3"><div class="col-md-8"><label class="form-label">Nombre</label><input id="m_name" class="form-control" value="${esc(x.name||'')}"></div><div class="col-md-4"><label class="form-label">Materia</label><select id="m_subject" class="form-select">${subjectOptions||'<option>Sin materias</option>'}</select></div><div class="col-12"><label class="form-label">Descripción</label><textarea id="m_desc" class="form-control">${esc(x.description||'')}</textarea></div><div class="col-md-4"><label class="form-label">Fecha de entrega</label><input id="m_date" type="date" class="form-control" value="${x.date||''}"></div><div class="col-md-4"><label class="form-label">Hora</label><input id="m_time" type="time" class="form-control" value="${x.time||''}"></div><div class="col-md-4"><label class="form-label">Prioridad</label><select id="m_priority" class="form-select">${['Alta','Media','Baja'].map(v=>`<option ${v===(x.priority||'Media')?'selected':''}>${v}</option>`).join('')}</select></div><div class="col-md-6"><label class="form-label">Estado</label><select id="m_status" class="form-select">${['Pendiente','En progreso','Completada'].map(v=>`<option ${v===(x.status||'Pendiente')?'selected':''}>${v}</option>`).join('')}</select></div></div>`,()=>{const n={id:id||uid(),name:m('m_name').value.trim(),subject:m('m_subject').value,description:m('m_desc').value,date:m('m_date').value,time:m('m_time').value,priority:m('m_priority').value,status:m('m_status').value};if(!n.name)return alert('Escribe el nombre de la tarea.');if(id)Object.assign(x,n);else state.tasks.push(n);saveState();closeModal();tasks();toast('Tarea guardada')})}
function completeTask(id){const x=state.tasks.find(a=>a.id===id);if(x){x.status='Completada';saveState();tasks();toast('Tarea completada ✓')}}

function teachers(){renderShell('teachers',`${pageHeader('👨‍🏫 Mis profesores','<button class="btn btn-primary" onclick="teacherForm()">➕ Agregar profesor</button>')}<div class="row g-3">${state.teachers.length?state.teachers.map(x=>`<div class="col-md-6 col-xl-4"><div class="cardx"><div class="d-flex justify-content-between"><h4 class="fw-bold">${esc(x.name)}</h4><button class="btn btn-sm btn-soft" onclick="toggleFavorite('${x.id}')">${x.favorite?'❤️':'♡'}</button></div><div class="muted">📚 ${esc(x.subject||'')}</div><div class="rating mt-2">${'★'.repeat(Math.max(0,Math.min(5,+x.rating||0)))}${'☆'.repeat(5-Math.max(0,Math.min(5,+x.rating||0)))}</div><p class="mt-2">${esc(x.notes||x.description||'')}</p><div class="action-row"><button class="btn btn-sm btn-soft" onclick="teacherForm('${x.id}')">Editar</button><button class="btn btn-sm btn-outline-danger" onclick="removeItem('teachers','${x.id}')">Eliminar</button></div></div></div>`).join(''):'<div class="col-12"><div class="empty">No hay profesores registrados.</div></div>'}</div>`)}
function teacherForm(id){const x=state.teachers.find(a=>a.id===id)||{};openModal(id?'Editar profesor':'Nuevo profesor',`<div class="row g-3"><div class="col-md-7"><label class="form-label">Nombre</label><input id="m_name" class="form-control" value="${esc(x.name||'')}"></div><div class="col-md-5"><label class="form-label">Materia</label><input id="m_subject" class="form-control" value="${esc(x.subject||'')}"></div><div class="col-md-7"><label class="form-label">Correo</label><input id="m_email" type="email" class="form-control" value="${esc(x.email||'')}"></div><div class="col-md-5"><label class="form-label">Valoración</label><select id="m_rating" class="form-select">${[0,1,2,3,4,5].map(v=>`<option ${+x.rating===v?'selected':''} value="${v}">${v} / 5</option>`).join('')}</select></div><div class="col-12"><label class="form-label">Observaciones privadas</label><textarea id="m_notes" class="form-control" rows="3">${esc(x.notes||'')}</textarea></div></div>`,()=>{const n={id:id||uid(),name:m('m_name').value.trim(),subject:m('m_subject').value.trim(),email:m('m_email').value.trim(),rating:+m('m_rating').value,notes:m('m_notes').value,favorite:x.favorite||false,description:x.description||''};if(!n.name)return alert('Escribe el nombre del profesor.');if(id)Object.assign(x,n);else state.teachers.push(n);saveState();closeModal();teachers();toast('Profesor guardado')})}
function toggleFavorite(id){const x=state.teachers.find(a=>a.id===id);if(x){x.favorite=!x.favorite;saveState();teachers()}}

function classmates(){renderShell('classmates',`${pageHeader('👥 Mis compañeros','<button class="btn btn-primary" onclick="classmateForm()">➕ Agregar compañero</button>')}<div class="row g-3">${state.classmates.length?state.classmates.map(x=>`<div class="col-md-6 col-xl-4"><div class="cardx"><h4 class="fw-bold">${esc(x.name)} ${esc(x.last)}</h4><div class="muted">${esc(x.nickname?'@'+x.nickname:'')}${x.course?' · '+esc(x.course):''}</div><p class="mt-2">${esc(x.notes||'')}</p><div class="action-row"><button class="btn btn-sm btn-soft" onclick="classmateForm('${x.id}')">Editar</button><button class="btn btn-sm btn-outline-danger" onclick="removeItem('classmates','${x.id}')">Eliminar</button></div></div></div>`).join(''):'<div class="col-12"><div class="empty">Agrega a tus compañeros para poder pasar asistencia.</div></div>'}</div>`)}
function classmateForm(id){const x=state.classmates.find(a=>a.id===id)||{};openModal(id?'Editar compañero':'Nuevo compañero',`<div class="row g-3"><div class="col-md-6"><label class="form-label">Nombre</label><input id="m_name" class="form-control" value="${esc(x.name||'')}"></div><div class="col-md-6"><label class="form-label">Apellido</label><input id="m_last" class="form-control" value="${esc(x.last||'')}"></div><div class="col-md-6"><label class="form-label">Apodo</label><input id="m_nick" class="form-control" value="${esc(x.nickname||'')}"></div><div class="col-md-6"><label class="form-label">Carrera/curso</label><input id="m_course" class="form-control" value="${esc(x.course||'')}"></div><div class="col-12"><label class="form-label">Observaciones</label><textarea id="m_notes" class="form-control">${esc(x.notes||'')}</textarea></div></div>`,()=>{const n={id:id||uid(),name:m('m_name').value.trim(),last:m('m_last').value.trim(),nickname:m('m_nick').value.trim(),course:m('m_course').value.trim(),notes:m('m_notes').value};if(!n.name)return alert('Escribe el nombre.');if(id)Object.assign(x,n);else state.classmates.push(n);saveState();closeModal();classmates();toast('Compañero guardado')})}

function attendance(){const total=state.classmates.length;const all=state.attendance.flatMap(a=>a.records||[]);const counts={Presente:all.filter(x=>x.status==='Presente').length,Ausente:all.filter(x=>x.status==='Ausente').length,Tarde:all.filter(x=>x.status==='Tarde').length};const pct=all.length?Math.round(counts.Presente/all.length*100):0;renderShell('attendance',`${pageHeader('✅ Control de asistencia')}<div class="row g-3"><div class="col-xl-7"><div class="cardx"><div class="row g-3"><div class="col-md-5"><label class="form-label">Fecha</label><input id="a_date" type="date" class="form-control" value="${new Date().toISOString().slice(0,10)}"></div><div class="col-md-7"><label class="form-label">Materia</label><select id="a_subject" class="form-select">${state.subjects.map(s=>`<option>${esc(s.name)}</option>`).join('')||'<option>Sin materias</option>'}</select></div></div><hr><div id="attendanceList">${state.classmates.length?state.classmates.map((c,i)=>`<div class="d-flex align-items-center justify-content-between gap-2 border-bottom py-2"><div><strong>${i+1}. ${esc(c.name)} ${esc(c.last)}</strong><div class="muted">${esc(c.course||'')}</div></div><select class="form-select form-select-sm att-status" data-id="${c.id}" style="max-width:150px"><option>Presente</option><option>Ausente</option><option>Tarde</option></select></div>`).join(''):'<div class="empty">Primero agrega compañeros.</div>'}</div><button class="btn btn-primary w-100 mt-3" onclick="saveAttendance()">💾 Guardar asistencia</button></div></div><div class="col-xl-5"><div class="row g-3"><div class="col-6"><div class="cardx"><div class="stat-value">${total}</div><div class="muted">👥 Estudiantes</div></div></div><div class="col-6"><div class="cardx"><div class="stat-value">${counts.Presente}</div><div class="muted">🟢 Presentes</div></div></div><div class="col-6"><div class="cardx"><div class="stat-value">${counts.Ausente}</div><div class="muted">🔴 Ausentes</div></div></div><div class="col-6"><div class="cardx"><div class="stat-value">${counts.Tarde}</div><div class="muted">🟡 Tardanzas</div></div></div></div><div class="cardx mt-3"><h4 class="fw-bold">📊 Asistencia</h4><div class="fs-2 fw-bold">${pct}%</div><div class="progress"><div class="progress-bar" style="width:${pct}%"></div></div></div></div></div><div class="cardx mt-3"><div class="section-heading"><h3>Historial</h3></div>${state.attendance.length?state.attendance.slice().reverse().map(a=>`<div class="d-flex justify-content-between border-bottom py-2"><span><strong>${formatDate(a.date)}</strong> · ${esc(a.subject)}</span><span class="muted">${a.records.length} registros</span></div>`).join(''):'<div class="empty">Aún no hay asistencias guardadas.</div>'}</div>`)}
function saveAttendance(){const records=[...document.querySelectorAll('.att-status')].map(s=>({studentId:s.dataset.id,status:s.value}));if(!records.length)return alert('No hay compañeros registrados.');state.attendance.push({id:uid(),date:m('a_date').value,subject:m('a_subject').value,records});saveState();attendance();toast('Asistencia guardada correctamente')}

function simpleCrud(key,title,fields,renderExtra=''){const arr=state[key];renderShell(key,`${pageHeader(title,`<button class="btn btn-primary" onclick="simpleForm('${key}','${title}',${JSON.stringify(fields)})">➕ Agregar</button>`)}${renderExtra}<div class="row g-3">${arr.length?arr.slice().reverse().map(x=>`<div class="col-md-6 col-xl-4"><div class="cardx"><h4 class="fw-bold">${esc(x.title||x.name||x.subject||'Registro')}</h4><div class="muted">${esc(x.date||'')} ${esc(x.time||'')}</div><p class="mt-2">${esc(x.description||x.notes||x.topic||x.type||'')}</p><div class="action-row"><button class="btn btn-sm btn-soft" onclick="simpleForm('${key}','${title}',${JSON.stringify(fields)},'${x.id}')">Editar</button><button class="btn btn-sm btn-outline-danger" onclick="removeItem('${key}','${x.id}')">Eliminar</button></div></div></div>`).join(''):'<div class="col-12"><div class="empty">No hay registros todavía.</div></div>'}</div>`)}
function simpleForm(key,title,fields,id){const x=state[key].find(a=>a.id===id)||{};openModal(id?'Editar '+title:'Nuevo '+title,fields.map(f=>`<div class="mb-3"><label class="form-label">${esc(fieldLabel(f))}</label><input id="sf_${f}" class="form-control" value="${esc(x[f]||'')}"></div>`).join(''),()=>{const n={id:id||uid()};fields.forEach(f=>n[f]=m('sf_'+f).value.trim());if(id)Object.assign(x,n);else state[key].push(n);saveState();closeModal();route();toast('Guardado correctamente')})}
function fieldLabel(x){return ({title:'Título',date:'Fecha',time:'Hora',type:'Tipo',description:'Descripción',subject:'Materia',room:'Aula',topic:'Tema',notes:'Observaciones'})[x]||x}
function calendar(){simpleCrud('events','evento',['title','date','time','type','description'])}
function exams(){simpleCrud('exams','examen',['subject','date','time','room','topic','notes'])}
function notes(){simpleCrud('notes','nota',['title','description'])}
function goals(){renderShell('goals',`${pageHeader('🎯 Mis objetivos','<button class="btn btn-primary" onclick="simpleForm(\'goals\',\'objetivo\',[\'title\',\'description\',\'progress\'])">➕ Agregar objetivo</button>')}<div class="row g-3">${state.goals.length?state.goals.map(x=>`<div class="col-md-6"><div class="cardx"><h4 class="fw-bold">${esc(x.title)}</h4><p class="muted">${esc(x.description||'')}</p><div class="d-flex justify-content-between"><span>Progreso</span><strong>${Math.min(100,+x.progress||0)}%</strong></div><div class="progress mt-1 mb-3"><div class="progress-bar" style="width:${Math.min(100,+x.progress||0)}%"></div></div><button class="btn btn-sm btn-soft" onclick="simpleForm('goals','objetivo',['title','description','progress'],'${x.id}')">Editar</button> <button class="btn btn-sm btn-outline-danger" onclick="removeItem('goals','${x.id}')">Eliminar</button></div></div>`).join(''):'<div class="col-12"><div class="empty">Agrega tu primer objetivo académico.</div></div>'}</div>`)}

function stats(){const tasks={done:state.tasks.filter(x=>x.status==='Completada').length,pending:state.tasks.filter(x=>x.status==='Pendiente').length,progress:state.tasks.filter(x=>x.status==='En progreso').length};const all=state.attendance.flatMap(a=>a.records||[]);const att={p:all.filter(x=>x.status==='Presente').length,a:all.filter(x=>x.status==='Ausente').length,t:all.filter(x=>x.status==='Tarde').length};const pct=all.length?Math.round(att.p/all.length*100):0;const fav=state.teachers.filter(x=>x.favorite).length;renderShell('stats',`${pageHeader('📊 Estadísticas')}<div class="row g-3"><div class="col-md-3"><div class="cardx"><div class="stat-value">${tasks.done}</div><div class="muted">Tareas completadas</div></div></div><div class="col-md-3"><div class="cardx"><div class="stat-value">${tasks.pending}</div><div class="muted">Pendientes</div></div></div><div class="col-md-3"><div class="cardx"><div class="stat-value">${tasks.progress}</div><div class="muted">En progreso</div></div></div><div class="col-md-3"><div class="cardx"><div class="stat-value">${pct}%</div><div class="muted">Asistencia</div></div></div></div><div class="row g-3 mt-1"><div class="col-lg-6"><div class="cardx"><h4 class="fw-bold">📝 Tareas</h4>${bar('Completadas',tasks.done,state.tasks.length)}${bar('Pendientes',tasks.pending,state.tasks.length)}${bar('En progreso',tasks.progress,state.tasks.length)}</div></div><div class="col-lg-6"><div class="cardx"><h4 class="fw-bold">✅ Asistencia</h4>${bar('Presentes',att.p,all.length)}${bar('Ausentes',att.a,all.length)}${bar('Tardanzas',att.t,all.length)}</div></div></div><div class="row g-3 mt-1"><div class="col-md-6"><div class="cardx"><div class="stat-value">${state.subjects.length}</div><div class="muted">📚 Materias</div></div></div><div class="col-md-6"><div class="cardx"><div class="stat-value">${state.teachers.length}</div><div class="muted">👨‍🏫 Profesores · ❤️ ${fav} favoritos</div></div></div></div>`)}
function bar(label,value,total){const p=total?Math.round(value/total*100):0;return `<div class="mb-3"><div class="d-flex justify-content-between"><span>${label}</span><strong>${value}</strong></div><div class="progress mt-1"><div class="progress-bar" style="width:${p}%"></div></div></div>`}

function scheduleForm(id){const x=state.schedule.find(a=>a.id===id)||{};openModal(id?'Editar clase':'Agregar clase',`<div class="row g-3"><div class="col-md-6"><label class="form-label">Día</label><select id="m_day" class="form-select">${DAYS.map((d,i)=>`<option value="${i}" ${+x.day===i?'selected':''}>${d}</option>`).join('')}</select></div><div class="col-md-6"><label class="form-label">Materia</label><input id="m_name" class="form-control" value="${esc(x.name||'')}"></div><div class="col-md-6"><label class="form-label">Profesor</label><input id="m_teacher" class="form-control" value="${esc(x.teacher||'')}"></div><div class="col-md-6"><label class="form-label">Aula</label><input id="m_room" class="form-control" value="${esc(x.room||'')}"></div><div class="col-md-6"><label class="form-label">Hora de inicio</label><input id="m_start" type="time" class="form-control" value="${x.start||''}"></div><div class="col-md-6"><label class="form-label">Hora de finalización</label><input id="m_end" type="time" class="form-control" value="${x.end||''}"></div></div>`,()=>{const n={id:id||uid(),day:+m('m_day').value,name:m('m_name').value.trim(),teacher:m('m_teacher').value.trim(),room:m('m_room').value.trim(),start:m('m_start').value,end:m('m_end').value,break:false};if(!n.name||!n.start||!n.end)return alert('Completa materia y horario.');if(id)Object.assign(x,n);else state.schedule.push(n);saveState();closeModal();schedule();toast('Clase guardada')})}
function removeSchedule(id){if(confirm('¿Eliminar esta clase?')){state.schedule=state.schedule.filter(x=>x.id!==id);saveState();schedule();toast('Clase eliminada')}}
function restoreSchedule(){if(confirm('¿Restaurar exactamente el horario original? Se perderán los cambios realizados en el horario.')){state.schedule=originalSchedule();seedFromSchedule(state);saveState();schedule();toast('Horario original restaurado')}}

function settings(){renderShell('settings',`${pageHeader('⚙️ Configuración')}<div class="row g-3"><div class="col-lg-7"><div class="cardx"><h4 class="fw-bold">Preferencias</h4><div class="form-check form-switch my-4"><input class="form-check-input" type="checkbox" id="themeSwitch" ${state.theme==='dark'?'checked':''} onchange="toggleTheme()"><label class="form-check-label">🌙 Modo oscuro</label></div><div class="form-check form-switch mb-4"><input class="form-check-input" type="checkbox" id="notificationSwitch" ${state.notifications?'checked':''} onchange="state.notifications=this.checked;saveState();toast('Preferencia guardada')"><label class="form-check-label">🔔 Alertas internas</label></div><div class="action-row"><button class="btn btn-primary" onclick="exportData()">💾 Exportar mis datos</button><label class="btn btn-soft">📥 Importar datos<input hidden type="file" accept="application/json" onchange="importData(event)"></label></div></div></div><div class="col-lg-5"><div class="cardx danger-zone"><h4 class="fw-bold">Zona de datos</h4><p class="muted">Todo se mantiene en localStorage de este navegador.</p><button class="btn btn-outline-danger" onclick="resetApp()">🗑️ Restablecer aplicación</button></div></div></div>`)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mi-asistente-datos.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('Datos exportados')}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!validState(x))throw new Error('Formato inválido');state=x;saveState();route();toast('Datos importados correctamente')}catch(err){alert('El archivo no tiene un formato válido para Mi Asistente.')}};r.readAsText(f)}
function resetApp(){if(confirm('¿Seguro que deseas borrar todos tus datos y restaurar el horario original?')){localStorage.removeItem(STORAGE_KEY);state=seedFromSchedule(emptyState());saveState();route();toast('Aplicación restaurada')}}

function globalSearch(q){const root=document.getElementById('searchResults');if(!root)return;const term=q.trim().toLowerCase();if(!term){root.innerHTML='';return}const results=[...state.subjects.map(x=>({t:'📚 '+x.name,h:'#subjects'})),...state.tasks.map(x=>({t:'📝 '+x.name,h:'#tasks'})),...state.teachers.map(x=>({t:'👨‍🏫 '+x.name,h:'#teachers'})),...state.classmates.map(x=>({t:'👥 '+x.name+' '+x.last,h:'#classmates'})),...state.schedule.filter(x=>!x.break).map(x=>({t:'📅 '+x.name+' · '+DAYS[x.day],h:'#schedule'}))].filter(x=>x.t.toLowerCase().includes(term)).slice(0,8);root.innerHTML=results.length?`<div class="search-results">${results.map(x=>`<a class="search-result" href="${x.h}" onclick="document.getElementById('searchResults').innerHTML=''">${esc(x.t)}</a>`).join('')}</div>`:`<div class="search-results"><div class="p-2 muted">Sin resultados.</div></div>`}
function toggleMenu(){document.getElementById('sidebar')?.classList.toggle('open')}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';saveState();applyTheme();if(location.hash==='#settings')settings()}
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark')}
function toast(message){const root=document.getElementById('toastRoot');if(!root)return;const el=document.createElement('div');el.className='toast-item';el.textContent=message;root.appendChild(el);setTimeout(()=>el.remove(),2500)}
function m(id){return document.getElementById(id)}
function openModal(title,body,onSave){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop-custom" role="dialog" aria-modal="true"><div class="modal-card"><div class="modal-head"><h3 class="h5 mb-0 fw-bold">${esc(title)}</h3><button class="btn btn-sm btn-soft" onclick="closeModal()" aria-label="Cerrar">✕</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" id="modalSave">Guardar</button></div></div></div>`;m('modalSave').onclick=onSave}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function removeItem(key,id){if(confirm('¿Eliminar este registro?')){state[key]=state[key].filter(x=>x.id!==id);saveState();route();toast('Registro eliminado')}}

function route(){const key=location.hash.slice(1)||'dashboard';const pages={dashboard,subjects,tasks,schedule,calendar,teachers,classmates,attendance,exams,stats,goals,notes,settings};(pages[key]||dashboard)();window.scrollTo(0,0)}
window.addEventListener('hashchange',route);
window.addEventListener('storage',()=>{state=loadState();route()});
setInterval(()=>{if((location.hash.slice(1)||'dashboard')==='dashboard')dashboard()},30000);
applyTheme();
route();
